num1 = eval(input('Enter the first number: '))
num2 = eval(input('Enter the second number: '))
num3 = eval(input('Enter the third number: '))
num4 = eval(input('Enter the fourth number: '))
num5 = eval(input('Enter the fifth number: '))
print('The average of the numbers you entered is', (num1+num2+num3+num4+num5)/5)
