name = input ('Enter your name: ')
print ('Hello, ', name)
num1 = eval(input('Enter the first number: '))
num2 = eval(input('Enter the second number: '))
num3 = eval(input('Enter the third number: '))
num4 = eval(input('Enter the fourth number: '))
num5 = eval(input('Enter the fifth number: '))
num6 = eval(input('Enter the sixth number: '))
num7 = eval(input('Enter the seventh number: '))
num8 = eval(input('Enter the eighth number: '))
print('The sum of the numbers you entered is', (num1+num2+num3+num4+num5+num6+num7+num8))
print('The average of the numbers you entered is', (num1+num2+num3+num4+num5+num6+num7+num8)/8)
